package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	SalesOrder    struct {
		SalesOrder     string `json:"document_no"`
		Plant          string `json:"deliver_to"`
		OrderQuantity  string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		NetPriceAmount string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema                string   `json:"api_schema"`
	Accepter                 []string `json:"accepter"`
	MaterialCode             string   `json:"material_code"`
	Supplier                 string   `json:"plant/supplier"`
	Stock                    string   `json:"stock"`
	SalesOrderType           string   `json:"document_type"`
	SONumber                 string   `json:"document_no"`
	ScheduleLineDeliveryDate string   `json:"planned_date"`
	ValidatedDate            string   `json:"validated_date"`
	Deleted                  bool     `json:"deleted"`
}

type SDC struct {
	ConnectionKey  string `json:"connection_key"`
	Result         bool   `json:"result"`
	RedisKey       string `json:"redis_key"`
	Filepath       string `json:"filepath"`
	CustomerReturn struct {
		CustomerReturn                string `json:"CustomerReturn"`
		CustomerReturnType            string `json:"CustomerReturnType"`
		SalesOrganization             string `json:"SalesOrganization"`
		DistributionChannel           string `json:"DistributionChannel"`
		OrganizationDivision          string `json:"OrganizationDivision"`
		SalesGroup                    string `json:"SalesGroup"`
		SalesOffice                   string `json:"SalesOffice"`
		SalesDistrict                 string `json:"SalesDistrict"`
		SoldToParty                   string `json:"SoldToParty"`
		CreationDate                  string `json:"CreationDate"`
		LastChangeDate                string `json:"LastChangeDate"`
		SenderBusinessSystemName      string `json:"SenderBusinessSystemName"`
		LastChangeDateTime            string `json:"LastChangeDateTime"`
		PurchaseOrderByCustomer       string `json:"PurchaseOrderByCustomer"`
		CustomerPurchaseOrderType     string `json:"CustomerPurchaseOrderType"`
		CustomerPurchaseOrderDate     string `json:"CustomerPurchaseOrderDate"`
		CustomerReturnDate            string `json:"CustomerReturnDate"`
		TotalNetAmount                string `json:"TotalNetAmount"`
		TransactionCurrency           string `json:"TransactionCurrency"`
		SDDocumentReason              string `json:"SDDocumentReason"`
		PricingDate                   string `json:"PricingDate"`
		RequestedDeliveryDate         string `json:"RequestedDeliveryDate"`
		ShippingType                  string `json:"ShippingType"`
		HeaderBillingBlockReason      string `json:"HeaderBillingBlockReason"`
		DeliveryBlockReason           string `json:"DeliveryBlockReason"`
		IncotermsClassification       string `json:"IncotermsClassification"`
		CustomerPaymentTerms          string `json:"CustomerPaymentTerms"`
		PaymentMethod                 string `json:"PaymentMethod"`
		CustomerTaxClassification1    string `json:"CustomerTaxClassification1"`
		RetsMgmtProcess               string `json:"RetsMgmtProcess"`
		ReferenceSDDocument           string `json:"ReferenceSDDocument"`
		ReferenceSDDocumentCategory   string `json:"ReferenceSDDocumentCategory"`
		CustomerReturnApprovalReason  string `json:"CustomerReturnApprovalReason"`
		SalesDocApprovalStatus        string `json:"SalesDocApprovalStatus"`
		RetsMgmtLogProcgStatus        string `json:"RetsMgmtLogProcgStatus"`
		RetsMgmtCompnProcgStatus      string `json:"RetsMgmtCompnProcgStatus"`
		RetsMgmtProcessingStatus      string `json:"RetsMgmtProcessingStatus"`
		OverallSDProcessStatus        string `json:"OverallSDProcessStatus"`
		TotalCreditCheckStatus        string `json:"TotalCreditCheckStatus"`
		OverallSDDocumentRejectionSts string `json:"OverallSDDocumentRejectionSts"`
		HeaderPartner                 struct {
			PartnerFunction string `json:"PartnerFunction"`
			Customer        string `json:"Customer"`
			Supplier        string `json:"Supplier"`
		} `json:"HeaderPartner"`
		CustomerReturnItem struct {
			CustomerReturnItem             string `json:"CustomerReturnItem"`
			HigherLevelItem                string `json:"HigherLevelItem"`
			CustomerReturnItemCategory     string `json:"CustomerReturnItemCategory"`
			CustomerReturnItemText         string `json:"CustomerReturnItemText"`
			PurchaseOrderByCustomer        string `json:"PurchaseOrderByCustomer"`
			Material                       string `json:"Material"`
			MaterialByCustomer             string `json:"MaterialByCustomer"`
			RequestedQuantity              string `json:"RequestedQuantity"`
			RequestedQuantityUnit          string `json:"RequestedQuantityUnit"`
			ItemGrossWeight                string `json:"ItemGrossWeight"`
			ItemNetWeight                  string `json:"ItemNetWeight"`
			ItemWeightUnit                 string `json:"ItemWeightUnit"`
			ItemVolume                     string `json:"ItemVolume"`
			ItemVolumeUnit                 string `json:"ItemVolumeUnit"`
			TransactionCurrency            string `json:"TransactionCurrency"`
			NetAmount                      string `json:"NetAmount"`
			MaterialGroup                  string `json:"MaterialGroup"`
			Batch                          string `json:"Batch"`
			ProductionPlant                string `json:"ProductionPlant"`
			StorageLocation                string `json:"StorageLocation"`
			ShippingPoint                  string `json:"ShippingPoint"`
			ShippingType                   string `json:"ShippingType"`
			DeliveryPriority               string `json:"DeliveryPriority"`
			IncotermsClassification        string `json:"IncotermsClassification"`
			CustomerPaymentTerms           string `json:"CustomerPaymentTerms"`
			ProductTaxClassification1      string `json:"ProductTaxClassification1"`
			SalesDocumentRjcnReason        string `json:"SalesDocumentRjcnReason"`
			ItemBillingBlockReason         string `json:"ItemBillingBlockReason"`
			ProfitCenter                   string `json:"ProfitCenter"`
			RetsMgmtProcess                string `json:"RetsMgmtProcess"`
			RetsMgmtProcessItem            string `json:"RetsMgmtProcessItem"`
			ReturnReason                   string `json:"ReturnReason"`
			RetsMgmtProcessingBlock        string `json:"RetsMgmtProcessingBlock"`
			CustRetItmFollowUpActivity     string `json:"CustRetItmFollowUpActivity"`
			ReturnsMaterialHasBeenReceived string `json:"ReturnsMaterialHasBeenReceived"`
			ReturnsRefundType              string `json:"ReturnsRefundType"`
			ReturnsRefundProcgMode         string `json:"ReturnsRefundProcgMode"`
			ReturnsRefundExtent            string `json:"ReturnsRefundExtent"`
			PrelimRefundIsDetermined       string `json:"PrelimRefundIsDetermined"`
			ReturnsRefundRjcnReason        string `json:"ReturnsRefundRjcnReason"`
			ReplacementMaterial            string `json:"ReplacementMaterial"`
			ReplacementMaterialQuantity    string `json:"ReplacementMaterialQuantity"`
			ReplacementMaterialQtyUnit     string `json:"ReplacementMaterialQtyUnit"`
			ReplacementMaterialIsRequested string `json:"ReplacementMaterialIsRequested"`
			ReplacementMatlSupplyingPlant  string `json:"ReplacementMatlSupplyingPlant"`
			NextPlantForFollowUpActivity   string `json:"NextPlantForFollowUpActivity"`
			ReturnsTransshipmentPlant      string `json:"ReturnsTransshipmentPlant"`
			Supplier                       string `json:"Supplier"`
			SupplierRetMatlAuthzn          string `json:"SupplierRetMatlAuthzn"`
			SuplrRetMatlAuthznIsRequired   string `json:"SuplrRetMatlAuthznIsRequired"`
			CustomerRetMatlInspResultCode  string `json:"CustomerRetMatlInspResultCode"`
			NextFllwUpActivityForMatlInsp  string `json:"NextFllwUpActivityForMatlInsp"`
			RetMatlInspResultCode          string `json:"RetMatlInspResultCode"`
			ProductIsInspectedAtCustSite   string `json:"ProductIsInspectedAtCustSite"`
			CustRetMatlAuthzn              string `json:"CustRetMatlAuthzn"`
			CRMLogicalSystem               string `json:"CRMLogicalSystem"`
			CRMObjectUUID                  string `json:"CRMObjectUUID"`
			CRMObjectID                    string `json:"CRMObjectID"`
			CRMObjectType                  string `json:"CRMObjectType"`
			RetsMgmtItmLogProcgStatus      string `json:"RetsMgmtItmLogProcgStatus"`
			RetsMgmtItmCompnProcgStatus    string `json:"RetsMgmtItmCompnProcgStatus"`
			RetsMgmtItmProcgStatus         string `json:"RetsMgmtItmProcgStatus"`
			ReturnsDocumentStatus          string `json:"ReturnsDocumentStatus"`
			ReturnsDocumentApprovalStatus  string `json:"ReturnsDocumentApprovalStatus"`
			SDProcessStatus                string `json:"SDProcessStatus"`
			ReferenceSDDocument            string `json:"ReferenceSDDocument"`
			ReferenceSDDocumentItem        string `json:"ReferenceSDDocumentItem"`
			ReferenceSDDocumentCategory    string `json:"ReferenceSDDocumentCategory"`
			SDDocumentRejectionStatus      string `json:"SDDocumentRejectionStatus"`
			ItemPricingElement             struct {
				CustomerReturn              string      `json:"CustomerReturn"`
				CustomerReturnItem          string      `json:"CustomerReturnItem"`
				PricingProcedureStep        string      `json:"PricingProcedureStep"`
				PricingProcedureCounter     string      `json:"PricingProcedureCounter"`
				ConditionType               string      `json:"ConditionType"`
				PricingDateTime             string      `json:"PricingDateTime"`
				ConditionCalculationType    string      `json:"ConditionCalculationType"`
				ConditionBaseValue          string      `json:"ConditionBaseValue"`
				ConditionRateValue          string      `json:"ConditionRateValue"`
				ConditionCurrency           string      `json:"ConditionCurrency"`
				ConditionQuantity           string      `json:"ConditionQuantity"`
				ConditionQuantityUnit       string      `json:"ConditionQuantityUnit"`
				ConditionCategory           string      `json:"ConditionCategory"`
				PricingScaleType            string      `json:"PricingScaleType"`
				ConditionRecord             string      `json:"ConditionRecord"`
				ConditionSequentialNumber   string      `json:"ConditionSequentialNumber"`
				TaxCode                     string      `json:"TaxCode"`
				ConditionAmount             string      `json:"ConditionAmount"`
				TransactionCurrency         string      `json:"TransactionCurrency"`
				PricingScaleBasis           string      `json:"PricingScaleBasis"`
				ConditionScaleBasisValue    string      `json:"ConditionScaleBasisValue"`
				ConditionScaleBasisUnit     string      `json:"ConditionScaleBasisUnit"`
				ConditionScaleBasisCurrency string      `json:"ConditionScaleBasisCurrency"`
				ConditionIsManuallyChanged  interface{} `json:"ConditionIsManuallyChanged"`
				ItemScheduleLine            struct {
					ScheduleLine                  string `json:"ScheduleLine"`
					OrderQuantityUnit             string `json:"OrderQuantityUnit"`
					ConfdOrderQtyByMatlAvailCheck string `json:"ConfdOrderQtyByMatlAvailCheck"`
					DeliveredQtyInOrderQtyUnit    string `json:"DeliveredQtyInOrderQtyUnit"`
					OpenConfdDelivQtyInOrdQtyUnit string `json:"OpenConfdDelivQtyInOrdQtyUnit"`
					DelivBlockReasonForSchedLine  string `json:"DelivBlockReasonForSchedLine"`
				} `json:"ItemScheduleLine"`
				ItemProcessStep struct {
					RetsMgmtProcess               string `json:"RetsMgmtProcess"`
					RetsMgmtProcessItem           string `json:"RetsMgmtProcessItem"`
					RetsMgmtProcItmQtySplit       string `json:"RetsMgmtProcItmQtySplit"`
					RetsMgmtProcessStep           string `json:"RetsMgmtProcessStep"`
					ReturnsDocumentType           string `json:"ReturnsDocumentType"`
					ReturnsDocument               string `json:"ReturnsDocument"`
					ReturnsDocumentItem           string `json:"ReturnsDocumentItem"`
					ReturnsDocumentStatus         string `json:"ReturnsDocumentStatus"`
					ReturnsDocumentApprovalStatus string `json:"ReturnsDocumentApprovalStatus"`
					ReturnsReferenceDocumentType  string `json:"ReturnsReferenceDocumentType"`
					ReturnsReferenceDocument      string `json:"ReturnsReferenceDocument"`
					ReturnsReferenceDocumentItem  string `json:"ReturnsReferenceDocumentItem"`
					RetsMgmtProcStepExecStatus    string `json:"RetsMgmtProcStepExecStatus"`
				} `json:"ItemProcessStep"`
			} `json:"ItemPricingElement"`
		} `json:"CustomerReturnItem"`
	} `json:"CustomerReturn"`
	APISchema        string   `json:"api_schema"`
	Accepter         []string `json:"accepter"`
	CustomerReturnNo string   `json:"customer_return"`
	Deleted          bool     `json:"deleted"`
}
